apiVersion: apps/v1
kind: Deployment
metadata:
  name: rust-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rust-api
  template:
    metadata:
      labels:
        app: rust-api
    spec:
      containers:
        - name: rust-api
          image: fredwinrosales/rust-api:__TAG__
          ports:
            - containerPort: 8000
          resources:
            requests:
              ephemeral-storage: "100Mi"
            limits:
              ephemeral-storage: "200Mi"
          imagePullPolicy: Always